// Code generated by 'yaegi extract github.com/slok/terraform-provider-goplugin/pkg/api/v1'. DO NOT EDIT.

package yaegicustom

import (
	"context"
	"github.com/slok/terraform-provider-goplugin/pkg/api/v1"
	"reflect"
)

func init() {
	Symbols["github.com/slok/terraform-provider-goplugin/pkg/api/v1/v1"] = map[string]reflect.Value{
		// type definitions
		"CreateResourceRequest":  reflect.ValueOf((*v1.CreateResourceRequest)(nil)),
		"CreateResourceResponse": reflect.ValueOf((*v1.CreateResourceResponse)(nil)),
		"DataSourcePlugin":       reflect.ValueOf((*v1.DataSourcePlugin)(nil)),
		"DeleteResourceRequest":  reflect.ValueOf((*v1.DeleteResourceRequest)(nil)),
		"DeleteResourceResponse": reflect.ValueOf((*v1.DeleteResourceResponse)(nil)),
		"NewDataSourcePlugin":    reflect.ValueOf((*v1.NewDataSourcePlugin)(nil)),
		"NewResourcePlugin":      reflect.ValueOf((*v1.NewResourcePlugin)(nil)),
		"ReadDataSourceRequest":  reflect.ValueOf((*v1.ReadDataSourceRequest)(nil)),
		"ReadDataSourceResponse": reflect.ValueOf((*v1.ReadDataSourceResponse)(nil)),
		"ReadResourceRequest":    reflect.ValueOf((*v1.ReadResourceRequest)(nil)),
		"ReadResourceResponse":   reflect.ValueOf((*v1.ReadResourceResponse)(nil)),
		"ResourcePlugin":         reflect.ValueOf((*v1.ResourcePlugin)(nil)),
		"UpdateResourceRequest":  reflect.ValueOf((*v1.UpdateResourceRequest)(nil)),
		"UpdateResourceResponse": reflect.ValueOf((*v1.UpdateResourceResponse)(nil)),

		// interface wrapper definitions
		"_DataSourcePlugin": reflect.ValueOf((*_github_com_slok_terraform_provider_goplugin_pkg_api_v1_DataSourcePlugin)(nil)),
		"_ResourcePlugin":   reflect.ValueOf((*_github_com_slok_terraform_provider_goplugin_pkg_api_v1_ResourcePlugin)(nil)),
	}
}

// _github_com_slok_terraform_provider_goplugin_pkg_api_v1_DataSourcePlugin is an interface wrapper for DataSourcePlugin type
type _github_com_slok_terraform_provider_goplugin_pkg_api_v1_DataSourcePlugin struct {
	IValue          interface{}
	WReadDataSource func(ctx context.Context, r v1.ReadDataSourceRequest) (*v1.ReadDataSourceResponse, error)
}

func (W _github_com_slok_terraform_provider_goplugin_pkg_api_v1_DataSourcePlugin) ReadDataSource(ctx context.Context, r v1.ReadDataSourceRequest) (*v1.ReadDataSourceResponse, error) {
	return W.WReadDataSource(ctx, r)
}

// _github_com_slok_terraform_provider_goplugin_pkg_api_v1_ResourcePlugin is an interface wrapper for ResourcePlugin type
type _github_com_slok_terraform_provider_goplugin_pkg_api_v1_ResourcePlugin struct {
	IValue          interface{}
	WCreateResource func(ctx context.Context, r v1.CreateResourceRequest) (*v1.CreateResourceResponse, error)
	WDeleteResource func(ctx context.Context, r v1.DeleteResourceRequest) (*v1.DeleteResourceResponse, error)
	WReadResource   func(ctx context.Context, r v1.ReadResourceRequest) (*v1.ReadResourceResponse, error)
	WUpdateResource func(ctx context.Context, r v1.UpdateResourceRequest) (*v1.UpdateResourceResponse, error)
}

func (W _github_com_slok_terraform_provider_goplugin_pkg_api_v1_ResourcePlugin) CreateResource(ctx context.Context, r v1.CreateResourceRequest) (*v1.CreateResourceResponse, error) {
	return W.WCreateResource(ctx, r)
}
func (W _github_com_slok_terraform_provider_goplugin_pkg_api_v1_ResourcePlugin) DeleteResource(ctx context.Context, r v1.DeleteResourceRequest) (*v1.DeleteResourceResponse, error) {
	return W.WDeleteResource(ctx, r)
}
func (W _github_com_slok_terraform_provider_goplugin_pkg_api_v1_ResourcePlugin) ReadResource(ctx context.Context, r v1.ReadResourceRequest) (*v1.ReadResourceResponse, error) {
	return W.WReadResource(ctx, r)
}
func (W _github_com_slok_terraform_provider_goplugin_pkg_api_v1_ResourcePlugin) UpdateResource(ctx context.Context, r v1.UpdateResourceRequest) (*v1.UpdateResourceResponse, error) {
	return W.WUpdateResource(ctx, r)
}
